- _announcements/DSA/Application Process.md
Ramesh,
Please approve the request for the above.
Thanks
> DSA - removal of express and normal course

- _about-us/Our Staff.md
Anita replaces Siow Xing Yu
Alex replaces Alisha Lim
> Updated FT for Sem 2 2023

- _cca/Visual & Performing Arts/Guzheng Ensemble.md
> Update Guzheng CCA Training Time

- _cca/Sports & Games/Softball.md
Hi, updated. For your approval please, Thanks
> Update of School Website for Softball CCA

- _quick-links/For Students.md
- pages/Home Based Learning (HBL).md
> HBL page update

- _about-us/Our Staff.md
> Mr Dan Yeo Info update

- _quick-links/School Canteen.md
> School Canteen - Stall Update

- _upcoming-events/2023 Open House.md
- index.md
> Rectified Open House Link Issue

- _co-curriculum/Uniformed Group/Girl Guides.md
- _co-curriculum/Uniformed Group/National Cadet Corps (NCC)(Land).md
- _co-curriculum/Uniformed Group/National Police Cadet Corps (NPCC).md
- index.md
> Rectified Open House Link again

- pages/School Newsletters.md
> School Newsletter Sep 2023

- _about-us/Achievements/Outstanding Alumnus.md
- _school-distinctive-programmes/Applied Learning Programme (ALP).md
- index.md
> Spell checks, page improvements, rectify missing images

- _resources/For Students.md
Re-upload for year changes. Pl approve it
> Class Timetable 2024

- _school-distinctive-programmes/Morning Musings.md
Updated the Morning Musings webpage to include the most recent sharing.
> Morning Musings - 07 Feb Update

- _school-distinctive-programmes/Morning Musings.md
- Added the sharing from this morning onto the webpage.
> Morning Musings 10 Feb Update

- pages/Home Based Learning (HBL).md
Edited the links for the HBL webpage.
> HBL webpage edits

- _school-distinctive-programmes/Morning Musings.md
Added the sharing video from this morning's FRC.
> Morning Musings update

- _about-us/Our Partners/Alumni.md
- _about-us/Our Partners/Parent Support Group.md
- _school-distinctive-programmes/Morning Musings.md
- Added specified messages to the PSG & Alumni webpages
- Added Musings sharing from morning FRC
> PSG, Alumni & Musings update

- _about-us/Our Partners/Parent Support Group.md
- _school-distinctive-programmes/Morning Musings.md
- Updated the PSG exco details as requested.
- Added the musings sharing from this morning.
> PSG & Musings update

- pages/Home Based Learning (HBL).md
- Changed the HBL links to reflect the 12 Mar ones.
> HBL update

- _school-distinctive-programmes/Morning Musings.md
- Added the sharing done this morning.
> Musings update

- _about-us/Our Partners/Alumni.md
- Updated the info on the Alumni page
> Alumni page update

- pages/Home Based Learning (HBL).md
Changed "Sec 4" to "Sec 4 & 5".
> Minor Edit for HBL page

- _about-us/Our Staff.md
- _co-curriculum/Sports & Games/Softball.md
> Our Staff page fix

- index.md
Added the announcement regarding school closure next week.
> Homepage Announcement Update

- pages/Home Based Learning (HBL).md
Updated the links for next week's HBL days.
> HBL updates for 15 - 17 July

- _upcoming-events/Save the Dates.md
Removed the HBL as instructed.
> Upcoming events page edit

- _co-curriculum/Sports & Games/Basketball.md
- _co-curriculum/Sports & Games/Fencing.md
- _co-curriculum/Sports & Games/Netball.md
- _co-curriculum/Uniformed Group/Girl Guides.md
- _co-curriculum/Uniformed Group/National Cadet Corps (NCC)(Land).md
- _co-curriculum/Uniformed Group/National Police Cadet Corps (NPCC).md
- _curriculum/Mother Tongue Language.md
- _curriculum/Physical Education (PE).md
Updated the respective pages with the information provided in the documents!
> MTL, P.E and CCA Achievement Updates

- _upcoming-events/Save the Dates.md
> Upcoming Events
